### PR TITLE
Remove workarounds for pre-2017 support

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-slsc-eds-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Remove workarounds that were in place to support versions of VeriStand prior to 2017. We no longer support these so this was dead code.

### Why should this Pull Request be merged?

Removing dead code means we have less to maintain.

### What testing has been done?

Built locally and confirmed things were still copied as expected.

### CODE REVIEW

**Review by buckd — COMMENTED** [review]
- [x] `build.toml` still has configuration for building packages for pre-2017 that needs to be removed.
- [x] Is this change intended to remove all dead code? The **CD_Version** conditional disable symbol still exists in the project and the structures using that symbol still exist in the files below.
image
- [x] Once the conditional symbol is removed, take the codegen step out of `build.toml`.

**Comment by rtzoeller** [comment]
> Is this change intended to remove all dead code?

It was a first pass, but I wasn't trying to be 100% thorough. I'll update it to include the items you've mentioned.

**Comment by buckd** [comment]
> It was a first pass, but I wasn't trying to be 100% thorough. I'll update it to include the items you've mentioned.

My question was probably incorrectly phrased. What I meant was "Is it intended to remove all version-specific workarounds?" I think the above changes should accomplish that and this will be good to go.

**Comment by rtzoeller** [comment]
@buckd I need to do some additional testing, but the code should be ready to review. I've removed as many usages of the conditional symbol as I could find, and cleaned up any related property reads that were obviously unnecessary.

**Review by niphilj — APPROVED** [review]

**Comment by Karl-G1** [comment]
Talking with @rtzoeller, this is just waiting on a re-review from @buckd. However, since it's close to 20.4 release window and this doesn't make any additive changes, let's not merge this into release/20.4 when it does go in. So no rush on your side to review, @buckd.

**Comment by rtzoeller** [comment]
I've disabled release branch merging for this repo, so this PR can submitted (at @buckd's leisure) without worrying about timing.

**Review by buckd — APPROVED** [review]

**Pull request merged**
