### PR TITLE
Added major improvements to the User Interface of the EDS Custom Devi…

### PR DESCRIPTION
**Pull request by Alexbarp**
...Based on the feedback of "https://github.com/NIVeriStandAdd-Ons/SLSC-EDS-Plugin-Custom-Device/issues": Fixed "Allow Channel Values to be changed on their pages", "Need abilirty to change Custom Device Name", "Multiproperty Value Application", "Import/Export Capability", "Set Busy/Unbusy When loading EDS from Cap file" as Improving the load time of the custom device.

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-slsc-eds-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

I fixed the UI experience of the EDS Custom Device (creating buttons and Runtime menus) that help you better control what the CD is supposed to do. Also I fixed several Issues of the custom device explained here:
https://github.com/NIVeriStandAdd-Ons/SLSC-EDS-Plugin-Custom-Device/issues

- "Allow Channel Values to be changed on their pages": added UI for the channel pages (and incorporated several UI aspects of the main page into it.

- "Need ability to change Custom Device Name": For version 2017 and up, I allow the CD to change the name (and customize as any other CD in VS). This was requested by Sales (Chris Bakker) and customer (Boing). In previous versions (2015/2016), this is not allowed and you can't change then. However, by default, the CD keep the same name and it won't cause back-compatibility problems.

-"Multiproperty Value Application": UI has multi-property support and better control of the columns used.

- "Import/Export Capability": Added button to import capability files, bin files, full bin files and configuration files (from other cards). Added export of the configuration (with the capability file embedded). Also added Runtime menu support for it.

"Set Busy/Unbusy When loading EDS from Cap file": The busy/unbusy was requested because it would take a long time to load the page. I improved considerably the load time, in the way that this request is not necessary anymore. Also, made other options (like refresh) and allow the user to have a bigger timeout for access resources.

### Why should this Pull Request be merged?

Because we have a lot of important changes that improve considerably the new Custom Device.

### What testing has been done?

I did a lot of manual test to validate that the new UI features work as expected. After this code is approved, we will be happy to work with R&D and add "manual tests" for it, so we can reproduce the test done. Also, I tested in VS 2017 and VS 2015, to be sure it works in both versions. Also, I improve quite a lot of use-cases.

### CODE REVIEW

**Comment by Alexbarp** [comment]
I will submit all the proposed changes above, except this one:

> * [ ]  The user interface glitches when I configure the module and the channel is "re-added" to the tree. This is distracting. Can you disable UI updates until the channel is completely updated?
> 
> image
 
This is related to how the SLSC Chassis behave in VS 2015/2016 and it doesn't require changes in the CD. However, in VS 2017, I could not see this behavior, so possibly this is not a problem for the latest versions of VS.

**Comment by buckd** [comment]
I'm only approving the changes for reverting unchanged files. Johann's review will gate this request.

**Comment by Alexbarp** [comment]
@csjall , were you able to review my latest change? Or you are done and I did not see your review?

**Comment by csjall** [comment]
@Alexbarp I will get to it today

**Pull request merged**
