### PR TITLE
Configure Reservation Groups

### LINKED ISSUE #32: Allow the EDS to be used with SLSC Switch
The EDS is designed to change any property of the card. The SLSC Switch is designed to control the switches. If you have a card that has "properties" and "switches" to be control (like the SLSC-12251), then you probably would need to have both functionalities. I think we should "expand" the SLSC-EDS to allow the card to support the switches AND have some properties available to change.
(*This was reported by Burt Snover from SET).

### PR DESCRIPTION
**Pull request by jacobson3**
fixes #32 

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-slsc-eds-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Allows users to configure the reservation group of an SLSC module being controlled by the EDS custom device. This enables users to read/write to the SLSC module from multiple sessions.

### Why should this Pull Request be merged?

This lets users configure properties using the EDS custom device while letting a separate switch custom device control the module's relays/connections.

### What testing has been done?

Ran EDS custom device while separate LabVIEW application was reading/writing properties. This caused an error before the change and worked after the change.

### CODE REVIEW

**Comment by rtzoeller** [comment]
One minor nit, but otherwise everything looks great! Thanks for cleaning up the `Compiled.Settings` control not having the right extension... I didn't even know LabVIEW could tolerate that.

- [ ] There's some inconsistencies in `Section Ref in` vs `Item Ref out` in `SLSC Get Reservation Values.vi` and `SLSC Set Reservation Values.vi`. Can you make them use the same term (section or item, but not both)?

**Comment by jacobson3** [comment]
> * [x]  There's some inconsistencies in `Section Ref in` vs `Item Ref out` in `SLSC Get Reservation Values.vi` and `SLSC Set Reservation Values.vi`. Can you make them use the same term (section or item, but not both)?

Done, also updated `Item Ref In` to be a required input as we discussed. There's also an update to the lvlib to move `SLSC Get Reservation Values.vi` into a virtual folder.

**Review by rtzoeller — APPROVED** [review]

**Pull request merged**
